/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2015-07-21 14:08:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Guerrilla gardening</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/reset.css\">\n");
      out.write("<script src=\"js/modernizr.custom.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"container\" style=\"width:100%;\">\n");
      out.write("\t\t\t<header class=\"top-bar\">\n");
      out.write("\t\t\t\t<h2 class=\"top-bar__headline\"></h2>\n");
      out.write("\t\t\t\t<div class=\"filter\">\n");
      out.write("\t\t\t\t\t<span>Filter by:</span>\n");
      out.write("\t\t\t\t\t<span class=\"dropdown\">Popular</span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</header>\n");
      out.write("\t\t\t<div id=\"main_icon\">\n");
      out.write("\t\t\t\t<!-- <img src=\"http://image.spreadshirtmedia.net/image-server/v1/designs/15486559,width=178,height=178/hand-grenade,-flowers,-guerilla-gardening.png\" style=\"width:120px;\"> -->\n");
      out.write("\t\t\t\t<div class=\"main_title_img\"><img src=\"http://i.imgur.com/37ipa4Z.jpg\" style=\"width:115px;\"></div>\n");
      out.write("\t\t\t\t<!-- <div class=\"main_title_img\"><img src=\"http://i.imgur.com/RnO4OrD.jpg\" style=\"width:170px;\"></div> -->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"main_title_con\">\n");
      out.write("\t\t\t\t\t<div class=\"main_title\">Guerrilla</div>\n");
      out.write("\t\t\t\t\t<div class=\"main_title2\">Gardening</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"theGrid\" class=\"main\">\n");
      out.write("\t\t\t\t<section class=\"grid\">\n");
      out.write("\t\t\t\t\t<a class=\"grid__item\" href=\"#\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"title title--preview\"></h2>\n");
      out.write("\t\t\t\t\t\t<div class=\"loader\"></div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"grid_img\">\n");
      out.write("\t\t\t\t\t\t\t<!-- <img src =\"http://i.imgur.com/f5IpKxe.png\"> -->\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- <span class=\"category\">Stories for humans</span> -->\n");
      out.write("\t\t\t\t\t\t<div class=\"meta meta--preview\">\n");
      out.write("\t\t\t\t\t\t\t<!-- <img class=\"meta__avatar\" src=\"img/authors/1.png\" alt=\"author01\" />  -->\n");
      out.write("\t\t\t\t\t\t\t<span class=\"meta__date\"><i class=\"fa fa-calendar-o\"></i> 9 Apr</span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"meta__reading-time\"><i class=\"fa fa-clock-o\"></i> 모집중</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t<a class=\"grid__item\" href=\"#\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"title title--preview\"></h2>\n");
      out.write("\t\t\t\t\t\t<div class=\"loader\"></div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"grid_img2\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"meta meta--preview\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"meta__date\"><i class=\"fa fa-calendar-o\"></i> 7 Apr</span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"meta__reading-time\"><i class=\"fa fa-clock-o\"></i> 마감</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t<a class=\"grid__item\" href=\"#\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"title title--preview\"></h2>\n");
      out.write("\t\t\t\t\t\t<div class=\"loader\"></div>\n");
      out.write("\t\t\t\t\t\t<span class=\"category\">Nutrition</span>\n");
      out.write("\t\t\t\t\t\t<div class=\"meta meta--preview\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"meta__avatar\" src=\"img/authors/3.png\" alt=\"author03\" /> \n");
      out.write("\t\t\t\t\t\t\t<span class=\"meta__date\"><i class=\"fa fa-calendar-o\"></i> 6 Apr</span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"meta__reading-time\"><i class=\"fa fa-clock-o\"></i> 2 min read</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t<a class=\"grid__item\" href=\"#\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"title title--preview\">Hope for Amy Walters</h2>\n");
      out.write("\t\t\t\t\t\t<div class=\"loader\"></div>\n");
      out.write("\t\t\t\t\t\t<span class=\"category\">Life &amp; Death</span>\n");
      out.write("\t\t\t\t\t\t<div class=\"meta meta--preview\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"meta__avatar\" src=\"img/authors/4.png\" alt=\"author04\" /> \n");
      out.write("\t\t\t\t\t\t\t<span class=\"meta__date\"><i class=\"fa fa-calendar-o\"></i> 6 Apr</span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"meta__reading-time\"><i class=\"fa fa-clock-o\"></i> 2 min read</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t<a class=\"grid__item\" href=\"#\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"title title--preview\">My Father told me...</h2>\n");
      out.write("\t\t\t\t\t\t<div class=\"loader\"></div>\n");
      out.write("\t\t\t\t\t\t<span class=\"category\">Nature vs. Nurture</span>\n");
      out.write("\t\t\t\t\t\t<div class=\"meta meta--preview\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"meta__avatar\" src=\"img/authors/5.png\" alt=\"author05\" /> \n");
      out.write("\t\t\t\t\t\t\t<span class=\"meta__date\"><i class=\"fa fa-calendar-o\"></i> 6 Apr</span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"meta__reading-time\"><i class=\"fa fa-clock-o\"></i> 2 min read</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t<a class=\"grid__item\" href=\"#\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"title title--preview\">What Happens in the Brain?</h2>\n");
      out.write("\t\t\t\t\t\t<div class=\"loader\"></div>\n");
      out.write("\t\t\t\t\t\t<span class=\"category\">Neuroscience</span>\n");
      out.write("\t\t\t\t\t\t<div class=\"meta meta--preview\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"meta__avatar\" src=\"img/authors/6.png\" alt=\"author06\" /> \n");
      out.write("\t\t\t\t\t\t\t<span class=\"meta__date\"><i class=\"fa fa-calendar-o\"></i> 6 Apr</span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"meta__reading-time\"><i class=\"fa fa-clock-o\"></i> 2 min read</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t<footer class=\"page-meta\">\n");
      out.write("\t\t\t\t\t\t<span>Load more...</span>\n");
      out.write("\t\t\t\t\t</footer>\n");
      out.write("\t\t\t\t</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div><!-- /container -->\n");
      out.write("\t\t<script src=\"js/classie.js\"></script>\n");
      out.write("\t\t<script src=\"js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
